# -*- coding: utf-8 -*-
"""final16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rczbtc-yeLvPG5Ov_UyAlLJgAsjQm5NO
"""

from datetime import datetime

def calculate_age():
    today = datetime.now()

    try:
        birth_date_input = input("กรอกวันเกิด (รูปแบบ DD/MM/YYYY): ")
        birth_date = datetime.strptime(birth_date_input, "%d/%m/%Y")

        age = today.year - birth_date.year

        # ถ้ายังไม่ถึงวันเกิดปีนี้ ให้ลบ 1
        if (today.month, today.day) < (birth_date.month, birth_date.day):
            age -= 1

        print(f"\nวันนี้คือ {today.strftime('%d/%m/%Y')}")
        print(f"คุณอายุ {age} ปี")

    except ValueError:
        print("❌ รูปแบบวันที่ไม่ถูกต้อง (ต้องเป็น DD/MM/YYYY)")

if __name__ == "__main__":
    calculate_age()