# -*- coding: utf-8 -*-
"""final16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rczbtc-yeLvPG5Ov_UyAlLJgAsjQm5NO
"""

from datetime import datetime

current_year = datetime.now().year

birth_year = int(input("กรอกปีเกิด (ค.ศ.): "))

age = current_year - birth_year

print(f"ปีปัจจุบันคือ {current_year}")
print(f"คุณอายุประมาณ {age} ปี")